project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "about.qmd"
    - "posts/**"
execute:
  freeze: true

jupyter: python3
engine: jupyter
  
website:
  title: "STSC2026"
  navbar:
    right:
      - icon: github    
        href: https://github.com/guebin/STSC2026
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2
format:
  html:
    theme: cosmo
    number-sections: false
    css: styles.css
    toc: true
    toc-location: right
    highlight-style: github
    toc-depth: 2