---
title: '05wk: 터미널의 이해 ~ Jupyterlab'
author: 최규빈
date: 04/01/2026
---

# 1. 터미널의 이해

`-` 윈도우 컴퓨터에서 아래의 명령어가 뭘 의미하는지 살펴보자. 

```bash
ls
mkdir asdf
cd asdf 
cd.. 
rmdir asdf
```

> 외우세요: 터미널을 열어준다 = 컴퓨터에 대한 제어권을 준다 

# 2. 터미널에서 조작하기

`-` 복사하기 & 붙여넣기

- 복사하기: 드래그 + 우클릭
- 붙여넣기: 우클릭

`-` 자동완성: 탭!!

# 3. 파이썬 설치방법 조사

`-` 파이썬 배우는 초보자에게 가장 어려운것!

- 선생님마다 설치하는 방법이 모두 다름 

`-` 왜 저렇게 설치방법이 다른가? 왜 다른 방법으로 각각 파이썬을 실행하는가? 이런것이 너무 어려움 

- [방법1:](https://wikidocs.net/8) 파이썬프로그램 다운로드 -> 시작버튼 눌러서 설치
- [방법2:](https://wikidocs.net/44) 아나콘다 설치 (그럼 자동으로 파이썬이 설치됨) 
- 방법3: 아나콘다 설치 + 가상환경 
- ... 

`-` 심지어 실행하는것도 다름

- [방법1:](https://goddaehee.tistory.com/286) 파이썬 프롬프트
- [방법2:](https://null-0.tistory.com/11) .py를 이용하여 실행?
- [방법3:](https://null-0.tistory.com/11) IDLE
- [방법4:](https://tariat.tistory.com/73) 파이참 
- [방법5:](https://shlee1990.tistory.com/963) 스파이더
- [방법6:](https://www.codingfactory.net/11337) Visual Studio Code
- 방법7: 주피터노트북, 주피터랩
    - 가상환경을 만들어서 해라.. 
    - 아나콘다 네비게이터에 주피터가 있다.. 
- ... 

`-` 머리아프니까 colab을 쓰라는 사람도 있음. 아니면 도커이미지를 줄테니까 그걸 쓰라는 사람도 있음. AWS를 쓰라는 사람도 있음..

`-` 핵심: 그냥 (1) 컴퓨터에 (2) 파이썬을 깔아서 (3) 실행하는 것임 

`-` 의문: 그런데 방법이 왜이렇게 많은가? 엑셀처럼 프로그램 설치하고 아이콘 더블클릭하면 끝나는 식으로 만들어야 하는것 아닌가? 

# 4. `python` 실행하고 살펴보기

`-` 윈도우에서 anaconda prompt 실행 -> python 

```bash
(base) C:\Users\python>python
```

```Python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> [1,2,3]+[4]
[1, 2, 3, 4]
>>> a=[1,2,3]+[4]
>>> a
[1, 2, 3, 4]
```

`-` 2개를 실행할 수도 있음. (두 환경은 각각 서로 독립적인 파이썬, 변수가 공유되지 않음) $\star$

`-` 아쉬운점: `?list'와 같이 도움말 기능이 동작하지 않음 

```Python
>>> ?list
  File "<stdin>", line 1
    ?list
    ^
SyntaxError: invalid syntax
>>> 
```

# 5. `python` 으로 코딩하기 (최악)

`-` 1부터 10까지 합을 구하는 프로그램을 만들고 싶음 

`-` 시도1: python을 키고 아래와 같이 실행 

```bash
(base) C:\Users\python>python
```

```Python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> total = 0
>>> for i in range(10):
...     total=total+i
...
>>> total
45
>>>
```

`-` 반성: 정답은 55인데 45가 출력되었다! $\to$ range(10)을 range(1,11)으로 바꿔야겠다! 

`-` 시도2: range(1,11)을 바꿔야겠다고 생각하고 다시 입력하다가 오타가 발생  

```Python
>>> total =0
>>> for i in range(1,11):
...     total = totla +i
...
```

- 앗 totla이라고 잘못쳤다. 

`-` 반성: 다음에는 정신을 똑바로 차려야겠다. 

# 6. `ipython` 실행하고 살펴보기

`-` 윈도우에서 anaconda prompt 실행 -> ipython 

```bash
(base) C:\Users\python>ipython
```

```Python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: a=[1,2,3]

In [2]: a
Out[2]: [1, 2, 3]

In [3]: a+[4]
Out[3]: [1, 2, 3, 4]
```

`-` `list?`가 가능 

```Python
In [4]: list?
Init signature: list(iterable=(), /)
Docstring:
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, DeferredConfigList, SList, _ImmutableLineList, FormattedText, NodeList, _ExplodedList, Stack, _Accumulator, ...

```

`-` 색깔이 알록달록해서 문법을 보기 편하다. (구문강조)

# 7. `ipython` 으로 코딩하기

`-` ipython을 사용한 프로그래머는 좀더 상황이 낫다 

```bash
(base) C:\Users\python>ipython
```

```Python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: total = 0

In [2]: for i in range(1,11):
   ...:     total = total + i
   ...:

In [3]: total
Out[3]: 55
```

# 8. 메모장 + `python`

`-` 메모장을 키고 아래의 내용을 적는다. 
```
total = 0 
for i in range(1,11): 
    total = total + i
print(total)
```

`-` 파일이름을 `mysum.py`로 저장한다. 

`-` anaconda prompt에서 `mysum.py`파일이 저장된 폴더로 이동 -> 실행 

```bash
(base) C:\Users\python>cd Desktop

(base) C:\Users\python\Desktop>dir
 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 9AFD-A05F

 C:\Users\python\Desktop 디렉터리

2022-03-27  오전 11:32    <DIR>          .
2022-03-27  오전 11:32    <DIR>          ..
2022-03-27  오전 12:01             2,306 Chrome.lnk
2022-03-26  오후 08:32             2,332 Microsoft Edge.lnk
2022-03-27  오전 11:33                71 mysum.py
               3개 파일               4,709 바이트
               2개 디렉터리  743,643,467,776 바이트 남음

(base) C:\Users\python\Desktop>python mysum.py
55

(base) C:\Users\python\Desktop>
```

`-` 소감

- 편한점1: 마우스를 이용하여 이동가능 
- 편한점2: 내가 작업한 내용은 바탕화면의 메모장에 저장이 되어있음
- 아쉬운점: ipython의 장점은 활용못함 (구문강조, 도움말기능) 

# 9. 메모장 + `ipython`

`-` 전체적인 개발방식

- 메모장: 코드를 편집, 저장 
- ipython: **anaconda prompt처럼 메모장의 코드를 실행하고 결과를 확인** + 구문강조, 도움말확인기능 등을 이용하여 짧은 코드를 빠르게 작성 

`-` 기능 

- ipython에서 **!python mysum.py**를 입력하면 anaconda prompt에서 **python mysum.py**를 입력한 것과 같은 효과
- ipython에서 **%run mysum**을 입력하면 메모장에서 mysum.py에 입력된 내용을 복사해서 ipython에 붙여넣어 실행한것과 같은 효과 

> `!` 는 터미널 명령을 훔쳐쓰는 기능. `%` 는 ipython 에서 제공하는 마법같은 기능. 이 두개를 잘 쓰면 ipynb에서 작업하기 매우 편리함. 

# 10. Jupyterlab

`-` 메모장과 ipython을 하나로 통합한 프로그램이 등장! 

- jupyter notebook, jupyter lab 
- spyder
- idle 
- VScode 
- ... 

`-` 주피터노트북, 혹은 주피터랩을 켜보자. 

```bash
(base) C:\Users\python>jupyter lab 
```

- 셀에서 1+1 수행
- 셀에서 `!dir` 등의 명령어 실행

`-` 주피터의 트릭 (실제로 주피터는 ipython에 기생할 뿐 아무런 역할도 안해요) 

1. 주피터를 실행 
2. 새 노트북을 생성
    - 컴퓨터는 내부적으로 ipython을 실행하고 그 ipython이랑 여러분이 방금만든 그 노트북과 연결 
3. 처음보이는 cell에 1+1을 입력 -> 쉬프트엔터 -> 결과2가 출력 
    - 처음보이는 cell하나 = 자동으로 열린 하나의 메모장
    - cell 1+1을 입력 = 메모장에 1+1을 적음 
    - 쉬프트+엔터후 결과2를 출력 = cell의 내용을 복사 -> ipython에 붙여넣음 -> ipython 계산된 결과를 복사 -> cell로 돌아와 붙여넣기 
4. 새로운 cell을 추가하고 2+2을 입력 -> 쉬프트엔터 -> 결과4가 출력 
    - 새로운 cell을 추가 = 새로운 메모장 추가
    - cell 2+2을 입력 = 새로운 메모장에 2+2를 적음 
    - 쉬프트+엔터후 결과4를 출력 = cell의 내용을 복사 -> ipython에 붙여넣음 -> ipython 계산된 결과를 복사 -> cell로 돌아와 붙여넣기

`-` 중요한 사실들 

- IDE는 내부적으로 연산을 수행하는 능력이 없다. (생각해볼것: 왜 R을 꼭 설치하고 Rstudio를 설치해야 했을까?) 
- 주피터에서 커널을 재시작한다는 의미는 메모장이 열린채로 ipython을 껐다가 다시 실행한다는 의미 
- 주피터는 단순히 '메모장의 내용을 복사하여 붙여넣는 기계'라고 볼 수 있다. 이렇게 생각하면 주피터는 꼭 ipython에 연결할 이유는 없다. 실제로 주피터에 R을 연결해서 쓸 수 있다. **즉 하나의 IDE가 여러개의 언어와 연결될 수 있다.**
- Jupyterlab이라는 프로그램은 크롬에 있는 내용과 ipython간의 통신을 제어하는 프로그램일 뿐이다. 

